# Generated by Django 4.2.11 on 2024-03-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0002_alter_booking_start_date'),
        ('room_booking', '0006_remove_room_image_url_room_image'),
    ]

    operations = [
    ]
