# Generated by Django 4.2.11 on 2024-03-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0007_merge_20240308_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
    ]
